using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Catalog.API.Entities
{
    public class Product
    {
        // MongoDB uses this field as the unique identifier for documents in a collection.
        [BsonId]
        // this property should be treated as an ObjectId, which is a specific type used by MongoDB 
        // for unique document identifiers. It's a 12-byte identifier typically generated by MongoDB itself.
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }
        // map that property to a field named "Name" in the MongoDB document. 
        // This is particularly useful when you want the field name in the database to be different from the property name in your class.
        [BsonElement("Name")]
        public string Name { get; set; }
        public string Category { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public decimal Price { get; set; }
    }
}